import { base44 } from '@/api/base44Client';

const oceanRegions = [
  { name: "Coral Triangle, SE Asia", latitude: -2.5, longitude: 125.0, risk_score: 87, risk_level: "critical", fishing_intensity: 92, ecosystem_fragility: 85, population_decline: 34, coral_coverage: 28, ocean_temp: 29.4, biodiversity_index: 9.2, protected_area: false, vessel_count: 342, anomalous_vessels: 18, recovery_status: "recommended", area_sq_km: 580000, ocean: "Pacific" },
  { name: "Great Barrier Reef", latitude: -18.3, longitude: 147.7, risk_score: 72, risk_level: "high", fishing_intensity: 55, ecosystem_fragility: 90, population_decline: 22, coral_coverage: 35, ocean_temp: 27.1, biodiversity_index: 8.8, protected_area: true, vessel_count: 89, anomalous_vessels: 5, recovery_status: "active", area_sq_km: 344400, ocean: "Pacific" },
  { name: "Gulf of Guinea", latitude: 3.0, longitude: 2.5, risk_score: 81, risk_level: "critical", fishing_intensity: 88, ecosystem_fragility: 72, population_decline: 41, coral_coverage: 8, ocean_temp: 28.2, biodiversity_index: 6.5, protected_area: false, vessel_count: 267, anomalous_vessels: 23, recovery_status: "none", area_sq_km: 240000, ocean: "Atlantic" },
  { name: "Mediterranean Basin", latitude: 36.5, longitude: 18.0, risk_score: 68, risk_level: "high", fishing_intensity: 75, ecosystem_fragility: 65, population_decline: 28, coral_coverage: 4, ocean_temp: 22.8, biodiversity_index: 7.1, protected_area: false, vessel_count: 456, anomalous_vessels: 12, recovery_status: "recommended", area_sq_km: 2500000, ocean: "Atlantic" },
  { name: "North Sea", latitude: 56.0, longitude: 3.0, risk_score: 45, risk_level: "moderate", fishing_intensity: 52, ecosystem_fragility: 40, population_decline: 15, coral_coverage: 1, ocean_temp: 12.3, biodiversity_index: 5.8, protected_area: false, vessel_count: 380, anomalous_vessels: 8, recovery_status: "none", area_sq_km: 570000, ocean: "Atlantic" },
  { name: "Maldives Reef System", latitude: 3.2, longitude: 73.2, risk_score: 76, risk_level: "critical", fishing_intensity: 60, ecosystem_fragility: 95, population_decline: 30, coral_coverage: 42, ocean_temp: 29.8, biodiversity_index: 8.5, protected_area: true, vessel_count: 78, anomalous_vessels: 4, recovery_status: "active", area_sq_km: 90000, ocean: "Indian" },
  { name: "Galápagos Marine Reserve", latitude: -0.9, longitude: -89.6, risk_score: 38, risk_level: "moderate", fishing_intensity: 22, ecosystem_fragility: 88, population_decline: 8, coral_coverage: 18, ocean_temp: 23.5, biodiversity_index: 9.5, protected_area: true, vessel_count: 34, anomalous_vessels: 6, recovery_status: "active", area_sq_km: 133000, ocean: "Pacific" },
  { name: "Barents Sea, Arctic", latitude: 74.0, longitude: 36.0, risk_score: 52, risk_level: "high", fishing_intensity: 45, ecosystem_fragility: 70, population_decline: 19, coral_coverage: 0, ocean_temp: 5.2, biodiversity_index: 4.2, protected_area: false, vessel_count: 112, anomalous_vessels: 9, recovery_status: "none", area_sq_km: 1400000, ocean: "Arctic" },
  { name: "South China Sea", latitude: 12.0, longitude: 114.0, risk_score: 91, risk_level: "critical", fishing_intensity: 95, ecosystem_fragility: 78, population_decline: 45, coral_coverage: 15, ocean_temp: 28.9, biodiversity_index: 7.8, protected_area: false, vessel_count: 523, anomalous_vessels: 31, recovery_status: "recommended", area_sq_km: 3500000, ocean: "Pacific" },
  { name: "Ross Sea, Antarctica", latitude: -75.0, longitude: 176.0, risk_score: 18, risk_level: "low", fishing_intensity: 12, ecosystem_fragility: 55, population_decline: 5, coral_coverage: 0, ocean_temp: -1.5, biodiversity_index: 6.1, protected_area: true, vessel_count: 12, anomalous_vessels: 1, recovery_status: "completed", area_sq_km: 1550000, ocean: "Southern" },
  { name: "Bay of Bengal", latitude: 15.0, longitude: 88.0, risk_score: 64, risk_level: "high", fishing_intensity: 70, ecosystem_fragility: 58, population_decline: 25, coral_coverage: 6, ocean_temp: 28.5, biodiversity_index: 6.8, protected_area: false, vessel_count: 198, anomalous_vessels: 14, recovery_status: "none", area_sq_km: 2172000, ocean: "Indian" },
  { name: "Caribbean Reef Network", latitude: 18.0, longitude: -75.0, risk_score: 59, risk_level: "high", fishing_intensity: 48, ecosystem_fragility: 82, population_decline: 20, coral_coverage: 22, ocean_temp: 27.5, biodiversity_index: 8.0, protected_area: false, vessel_count: 145, anomalous_vessels: 7, recovery_status: "recommended", area_sq_km: 264000, ocean: "Atlantic" },
];

const vesselAlerts = [
  { vessel_name: "FV Hai Long 28", alert_type: "ais_gap", severity: "high", region_name: "South China Sea", latitude: 11.5, longitude: 113.8, description: "Vessel AIS signal lost for 18 hours in contested fishing zone near Spratly Islands.", duration_hours: 18, status: "active" },
  { vessel_name: "MV Pacific Star", alert_type: "loitering", severity: "medium", region_name: "Coral Triangle, SE Asia", latitude: -3.1, longitude: 126.2, description: "Vessel loitering for extended period near protected coral reef area.", duration_hours: 36, status: "investigating" },
  { vessel_name: "FV Okyanos III", alert_type: "boundary_violation", severity: "high", region_name: "Galápagos Marine Reserve", latitude: -1.2, longitude: -89.3, description: "Industrial fishing vessel detected within marine reserve boundary.", duration_hours: 6, status: "active" },
  { vessel_name: "SV Dark Runner", alert_type: "dark_vessel", severity: "high", region_name: "Gulf of Guinea", latitude: 2.8, longitude: 3.1, description: "Unidentified vessel operating without AIS. Satellite imagery suggests trawling activity.", duration_hours: 48, status: "active" },
  { vessel_name: "FV Neptuno Azul", alert_type: "speed_anomaly", severity: "medium", region_name: "Mediterranean Basin", latitude: 35.8, longitude: 17.5, description: "Erratic speed patterns inconsistent with declared fishing activity.", duration_hours: 12, status: "active" },
  { vessel_name: "MV Sagar Deep", alert_type: "loitering", severity: "low", region_name: "Bay of Bengal", latitude: 14.5, longitude: 87.2, description: "Cargo vessel anchored in known transshipment zone for extended period.", duration_hours: 72, status: "investigating" },
  { vessel_name: "FV Jin Sheng 7", alert_type: "ais_gap", severity: "high", region_name: "South China Sea", latitude: 13.2, longitude: 115.6, description: "AIS signal intermittent over 5-day period. Pattern suggests intentional signal manipulation.", duration_hours: 120, status: "active" },
  { vessel_name: "FV Atlantic Dawn", alert_type: "boundary_violation", severity: "medium", region_name: "North Sea", latitude: 55.3, longitude: 2.8, description: "Vessel detected fishing within seasonal closure zone during spawning period.", duration_hours: 8, status: "resolved" },
  { vessel_name: "FV Coral Hunter", alert_type: "loitering", severity: "high", region_name: "Great Barrier Reef", latitude: -17.8, longitude: 147.2, description: "Fishing vessel loitering in critical coral recovery zone.", duration_hours: 24, status: "active" },
  { vessel_name: "MV Phantom Catch", alert_type: "dark_vessel", severity: "high", region_name: "Coral Triangle, SE Asia", latitude: -2.0, longitude: 124.5, description: "Satellite detected vessel with no AIS, radar, or VMS signals in high-biodiversity zone.", duration_hours: 96, status: "active" },
  { vessel_name: "FV Arctic Prowler", alert_type: "ais_gap", severity: "medium", region_name: "Barents Sea, Arctic", latitude: 73.5, longitude: 35.0, description: "AIS gap detected during heavy fishing activity. Signal resumed 200km from last position.", duration_hours: 14, status: "investigating" },
];

const conservationReports = [
  { title: "Critical Risk Assessment: South China Sea Overfishing Crisis", region_name: "South China Sea", report_type: "risk_assessment", summary: "The South China Sea has reached critical risk levels with a Marine Risk Score of 91/100. Fish populations have declined by 45% over the past decade.", content: "## Executive Summary\n\nThe South China Sea represents the highest-risk marine zone in our global monitoring network.\n\n## Key Findings\n\n- **Fish population decline of 45%** over the monitoring period\n- **95% fishing intensity** — one of the highest globally\n- **31 anomalous vessel detections** including AIS gaps\n- Coral coverage dropped to 15%\n\n## Recommendations\n\n1. Implement seasonal fishing moratoriums\n2. Increase satellite surveillance\n3. Establish temporary no-take zones\n4. Coordinate multinational enforcement", risk_score_at_time: 91, recommendations: ["Implement seasonal fishing moratoriums", "Increase satellite surveillance", "Establish temporary no-take zones"], status: "published" },
  { title: "Recovery Plan: Great Barrier Reef Coral Restoration", region_name: "Great Barrier Reef", report_type: "recovery_plan", summary: "Comprehensive recovery strategy focusing on reducing fishing pressure and monitoring coral regrowth.", content: "## Recovery Strategy\n\nLeverages existing marine protected area designations with enhanced monitoring.\n\n## Phase 1 (0-6 months)\n\n1. Expand no-take zones by 15%\n2. Deploy additional monitoring buoys\n3. Increase patrol frequency\n\n## Phase 2 (6-24 months)\n\n1. Implement coral gardening programs\n2. Reduce agricultural runoff\n3. Community-based monitoring\n\n## Expected Outcomes\n\nProjected risk score reduction to 55/100 within 24 months.", risk_score_at_time: 72, recommendations: ["Expand no-take zones by 15%", "Deploy monitoring buoys", "Implement coral gardening programs"], status: "published" },
  { title: "Trend Analysis: Gulf of Guinea Dark Vessel Activity", region_name: "Gulf of Guinea", report_type: "trend_summary", summary: "Analysis of increasing dark vessel activity with 23 anomalous vessel detections.", content: "## Trend Overview\n\nDark vessel activity has increased by 35% over the past quarter.\n\n## Key Patterns\n\n- **23 anomalous vessels** detected (up from 15)\n- Activity peaks between 22:00-04:00 local time\n- Concentrated near EEZ boundaries\n- Fish population decline at 41%\n\n## Recommendations\n\n1. Deploy additional satellite monitoring\n2. Coordinate coast guard rapid response\n3. Implement vessel whitelist system", risk_score_at_time: 81, recommendations: ["Deploy satellite monitoring", "Coordinate coast guard response", "Implement vessel whitelist"], status: "published" },
];

export async function seedDataIfEmpty() {
  const existing = await base44.entities.OceanRegion.list();
  if (existing.length > 0) return false;

  await base44.entities.OceanRegion.bulkCreate(oceanRegions);
  await base44.entities.VesselAlert.bulkCreate(vesselAlerts);
  await base44.entities.ConservationReport.bulkCreate(conservationReports);
  return true;
}